all the action are moved to single file

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -17,7 +17,7 @@ jobs:
           fetch-depth: 2
 
       - name: Set up Node.js
-        uses: actions/setup-node@v2
+        uses: actions/setup-node@v3
         with:
           node-version: "18"
 
@@ -89,3 +89,69 @@ jobs:
           fi
         env:
           CHANGED_FILES: ${{ env.CHANGED_FILES }}
+
+  unit_test:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Run Unit Tests
+        run: |
+          npm install
+          npm test
+
+  merge_to_dev:
+    runs-on: ubuntu-latest
+    needs: [lint, unit_test]
+    if: ${{ needs.lint.result == 'success' && needs.unit_test.result == 'success' }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Set up Git credentials
+        run: |
+          git config --global user.email hazrat17016@gmail.com
+          git config --global user.name "Hazrat16"
+
+      - name: Get branch name
+        id: get_branch
+        run: |
+          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
+
+      - name: Debug information
+        run: |
+          echo "Branch to merge: ${{ env.BRANCH_NAME }}"
+          git branch -a
+          git log --oneline --decorate --graph --all
+          git fetch origin
+          git branch -r
+
+      - name: Checkout dev branch
+        run: |
+          git fetch origin dev
+          git checkout dev
+          git pull origin dev
+
+      - name: Fetch feature branch
+        run: |
+          git fetch origin ${{ env.BRANCH_NAME }}
+          git checkout ${{ env.BRANCH_NAME }}
+
+      - name: Attempt to Merge Feature Branch into Dev
+        run: |
+          git checkout dev
+          git merge --no-ff ${{ env.BRANCH_NAME }} || {
+            echo "Merge failed. Details:";
+            git status;
+            git diff;
+            exit 1;
+          }
+
+      - name: Push changes to dev
+        if: success()
+        env:
+          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
+        run: |
+          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
+          git push origin dev
